@startuml
rectangle Market {
    (Put item up for sale) as (sell)
    (Remove item from market) as (sold)
    (Look for new items) as (observe)
}

Buyer -up-> (observe)

Seller -up-> (sell)
Seller -up-> (sold)


@enduml